CFLAGS= -Wall -g -O -std=c++11
INC_ADETL= -I/Users/BlackIce/Documents/Library/ADETL

#INC_ADETL= -I/home/blackicefc/Documents/Library/ADETL
SRC= *.cpp 

all:
	g++ $(CFLAGS) $(INC_ADETL) $(SRC) -o ./run

clean:
	rm -f ./run ./*~
